apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    app: {{ include "nginx-ingress.name" . }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nginx-ingress.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nginx-ingress.name" . }}
    spec:
      containers:
        - name: nginx-ingress
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
