apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - name: http
      port: {{ .Values.controller.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/name: {{ include "nginx-ingress.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

