apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-ingress.fullname" . }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: 80
  selector:
    app: {{ include "nginx-ingress.name" . }}
